### ISSUE TITLE
[Topic Idea] How To Use Git

### ISSUE THREAD

**Issue by yangc95** [Codecademy/ugc#18]
Beginner-friendly content on how to use Git, starting with how a Git repository is created when the `git init` command is run in the CLI (command-line interface). Many common Git commands can be found on Codecademy Docs under the [Git](https://www.codecademy.com/resources/docs/git) topic. Definitely consider linking to the Docs entries for this piece.

Images and diagrams are highly recommended.

Let us know if you want to write this!

**Comment by FrancineBlanc** [comment]
Hi there

If I wished to write this content on how to use Git, how can I start and when would the article need to be written by?

Best wishes
Francine

**Comment by sonnynomnom** [comment]
Assigning you the article @FrancineBlanc! You can start writing on your local computer and then add your article to the repo when it's done and make a Pull Request. Take a look at the instructions in the README.

If you can do it within 10 days, that will be great!
