### ISSUE TITLE
[Topic Idea] Create a URL Using Slugs

### ISSUE THREAD

**Issue by yangc95** [Codecademy/ugc#19]
A slug is what you see at the end of a URL. For some sites like [Pinterest](https://www.pinterest.com/), when you click to access a particular item (in our example, it’s a pin), the URL will read something like https://www.pinterest.com/pin/914862416083562/. This long number is probably an identifier for the pin as it’s retrieved from the database, but it holds little value in representing the pin image contents.  

When slugs are fine-tuned, they benefit SEO (Search Engine Ranking). Users can find relevant content they want to read, and websites get more traffic. It’s a win-win!

 Feel free to put your creative spin on this 🎨 💻 

Let us know if you want to write this!

**Comment by CBID2** [comment]
Is this issue still open @yangc95? If so, I’ll give it a try! :)

**Comment by yangc95** [comment]
@CBID2 Yeah, this issue it still open! UGC articles are tutorials so the formatting is much more forgiving than something like Docs.

How did you discover this repo btw?

**Comment by CBID2** [comment]
> @CBID2 Yeah, this issue it still open! UGC articles are tutorials so the formatting is much more forgiving than something like Docs.
> 
> 
> 
> How did you discover this repo btw?

Thanks @yangc95! I discovered this repo through a randomish search. I got curious about the other repos Codeacademy has.

**Comment by yangc95** [comment]
@CBID2 cool 😎 that's good to know

These are a little more open-ended and may take a longer time to compose and review - glad to have you on this repo as well!

**Comment by CBID2** [comment]
> @CBID2 cool 😎 that's good to know
> 
> These are a little more open-ended and may take a longer time to compose and review - glad to have you on this repo as well!

Hi @yangc95! :) Here's my PR: #56
