### ISSUE TITLE
[Topic Idea] Create a Queue

### ISSUE THREAD

**Issue by yangc95** [Codecademy/ugc#21]
A queue is an abstract data type (ADT) that follows the first-in, first-out protocol. Think of standing in a line for purchasing an item. The first person on the line is the first one that exits the line and the last person on the line is the last one to exit.

There are different ways we can create a queue. One way is through using an array. Another is through a linked list where each “person in the line” is a node. 

Some suggested terms:

- First in, first-out (FIFO) protocol
- `enqueue`
- `dequeue`
- `peek`

Get creative with your example code snippets and keep it original 👍 Tack on the language used for this piece at the end of the title, ex: "Create a Queue in Python."

Let us know if you want to write this!

**Comment by deyemiobaa** [comment]
Hi, @yangc95. I would love to write about Creating Queues using JavaScript.
