### ISSUE TITLE
[Topic Idea] How To Use GraphQL

### ISSUE THREAD

**Issue by yangc95** [Codecademy/ugc#26]
[GraphQL](https://www.codecademy.com/resources/docs/general/graphql) is an open-source query language used for APIs. Originally created by Meta (formerly known as Facebook), it is compatible with many languages including Ruby, JavaScript, and Java.

Get creative with the example code snippets and keep it original.

Let us know if you want to write this!

**Comment by yangc95** [comment]
Hi @Smyja,

Welcome to the User Generated Content (UGC) repo! Glad to have you here 🙂 we're excited to see your original content.

> I'll go ahead and assign you this issue. After you submit a PR (pull request) within (give or take) 10 days, our team will review it.
> 
> Check out the [Contribution Guide](https://github.com/Codecademy/ugc/blob/main/.github/CONTRIBUTING.md) and
> [Documentation folder](https://github.com/Codecademy/ugc/tree/main/documentation) for further instructions and you can always reach out on this thread if you have any questions!

**Comment by Smyja** [comment]
> Hi @Smyja,
> 
> Welcome to the User Generated Content (UGC) repo! Glad to have you here 🙂 we're excited to see your original content.
> 
> > I'll go ahead and assign you this issue. After you submit a PR (pull request) within (give or take) 10 days, our team will review it.
> > Check out the [Contribution Guide](https://github.com/Codecademy/ugc/blob/main/.github/CONTRIBUTING.md) and
> > [Documentation folder](https://github.com/Codecademy/ugc/tree/main/documentation) for further instructions and you can always reach out on this thread if you have any questions!

Hey, should the focus be on building an Api with graphql or on consuming a graphql api? I was consuming a graphql api with ReactJs. I built the graphql api with Django.

**Comment by Dusch4593** [comment]
hey @Smyja feel free to go with whatever you're comfortable writing about! I would personally choose to write an article about building a graphql api first, as it would get a reader nicely familiar with how they're commonly made. 😄

**Comment by yangc95** [comment]
@Smyja Just wanted to say, hope everything is going well! Excited to see what you come up with ☺️

**Comment by Smyja** [comment]
> @Smyja Just wanted to say, hope everything is going well! Excited to see what you come up with ☺️

Thanks for reaching out, I have been indisposed and I am almost done with it.

**Comment by yangc95** [comment]
@Smyja hope you've had time to rest and are feeling better! Thanks for the previous quick response, also ty for your patience ☺️
