### ISSUE TITLE
[Topic Idea] Introduction To ADTs

### ISSUE THREAD

**Issue by yangc95** [Codecademy/ugc#30]
A beginner-friendly introduction to abstract data types (ADTs).

Some suggested terms (not limited to):

- Stack
- Queue
- Linked-list
- Graph
- Binary Tree

Get creative with your example code snippets and keep it original 👍 Tack on the language used for this piece at the end of the title, ex: “Introduction to ADTs in Java.”

Let us know if you want to write this!

**Comment by Goku-kun** [comment]
Hey, @yangc95. I'll take up this issue. Writing up details on specific data structures. 

I plan to implement documents for each of these ADTs with general information about the ADTs first, followed with language specific implementation (mostly in Python and JavaScript).

**Comment by Goku-kun** [comment]
Hey @yangc95.

Thank you for assigning this issue to me. I was thinking of creating a single document which will be formatted as follows: 

1. Abstract Data Type Introduction
2.  a. Linked-list introduction
     b. Linked-list introduction in JS using arrays and nodes (Yes, two implementations)
     c. Linked-list introduction in Python using lists and nodes (Two implementations here as well)
3. Stacks and so on....

But the structure remains the same. So, should I create two different files that keep the same explanatory content but language specific code and implementation? Or stick to the above mentioned structure?

**Comment by Goku-kun** [comment]
I suppose it's not really about the implementation so I can choose one language and stick with it. There's no need to provide information in different languages if there isn't any implementation code.

**Comment by Goku-kun** [comment]
#51 will address this issue so I'll just link it here.
