### ISSUE TITLE
[Topic Idea] Build a Full-Stack App with Ruby on Rails

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/ugc#53]
Write a tutorial article that teaches readers how to build a small full-stack application with the Ruby on Rails framework. This should include the following:

- A prerequisite section detailing what competencies and technologies the readers will need to complete the tutorial.
- Building a back-end with Active Record models, Action Controllers, and Routing.
- Designing a front-end with Action View.

You can be as creative with the idea for the application as you'd like but it should be relatively small (like a [minimum viable product](https://en.wikipedia.org/wiki/Minimum_viable_product)). Please keep the content original 👍🏻.

**Comment by deyemiobaa** [comment]
Hi @Dusch4593. Please assign this to me 😀

**Comment by Dusch4593** [comment]
@deyemiobaa Assigned!
