### ISSUE TITLE
[Topic Idea] NextJs Deployment with Caprover and Github Actions

### ISSUE THREAD

**Issue by smyja** [Codecademy/ugc#55]
I'd like to write on how to deploy the NextJs 13 on Caprover using Github Actions since most persons are starting their indie hacker journeys, i believe this would be great for many persons. @KTom101

**Comment by KTom101** [comment]
@smyja Hi! This sounds very interesting thank you for reaching out. Do you have an outline of what you're going to include?

**Comment by smyja** [comment]
Sure, here is an outline for the article.

## Introduction

- What is Next.js?

- What is Caprover?

- What are Github Actions?

## Why use Next.js, Caprover, and Github Actions together?

- Setting Up Caprover on Digital ocean 

- Create a Caprover account

- Create a new application in Caprover

- Configure Caprover to use your Github repository

- Setting Up Github Actions

- Create a new Github Action workflow

- Add a step to build your Next.js application

-Add a step to deploy your Next.js application to Caprover

## Testing Your Deployment

- Open your Next.js application in a web browser

- Verify that your application is working properly

## Conclusion

Summary of the steps involved in deploying a Next.js application with Caprover and Github Actions

Resources for learning more about Next.js, Caprover, and Github Actions

**Comment by KTom101** [comment]
@smyja Ok great, I've just assigned this to you! Please try to be as clear as possible, add images when possible (keep image sizes to less than 1MB each), and add links to the tools mentioned. If you need help with something, feel free to let us know 👍

**Comment by smyja** [comment]
> 

Great.

**Comment by smyja** [comment]
> @smyja Ok great, I've just assigned this to you! Please try to be as clear as possible, add images when possible (keep image sizes to less than 1MB each), and add links to the tools mentioned. If you need help with something, feel free to let us know 👍

is it okay if i create a draft pull request then set it to ready for review when i am done? or only create when i am done.

**Comment by KTom101** [comment]
@smyja You can have is as a draft first. Just remember to take it out of draft status when you're done.

**Comment by smyja** [comment]
> @smyja You can have it as a draft first. Just remember to take it out of draft status when you're done.

hey, any update on this? been a month now.
